### ISSUE TITLE
Compare to src imports

### ISSUE THREAD

**Issue by prog-rajkamal** [pksunkara/vue-builder-webpack-plugin#1]
I just saw this project link at hacker news and got curious on  what this project offer over [src imports](https://vue-loader.vuejs.org/en/start/spec.html)?

source imports, basically, you to split vue component over different html, css and js files.

**Comment by denismorozov** [comment]
I guess the difference is that you don't have to define a Vue file to bind them all together.

**Comment by pksunkara** [comment]
I am so sorry. I don't have notifications enabled for this repo and I completely missed everything. I am going to look into it this week.

**Comment by pksunkara** [comment]
Yup, the different is that this project helps you do that automatically from the different sources you have instead of doing the dredging work of defining a vue file for everything.
