### ISSUE TITLE
Allow configure folder for files

### ISSUE THREAD

**Issue by CKGrafico** [pksunkara/vue-builder-webpack-plugin#11]
What do you think about this feature?

Allow to configure as param, a folder where store all the .vue files (could be useful, to use a .temp folder and ignore it)

**Comment by pksunkara** [comment]
Hmm.. Might need a bit of testing. But as I said in the others issue, PRs are welcome.

**Comment by pksunkara** [comment]
This won't be needed now.

**Comment by CKGrafico** [comment]
Only to add more info is someone arrives here:
Won't need because with my last PR files are virtual, you don't need more physical files
