### ISSUE TITLE
Doing the same but took the loader option.

### ISSUE THREAD

**Issue by Rouche** [pksunkara/vue-builder-webpack-plugin#13]
Hi,

This is funny because i was doing the same exact thing except from a Loader, configured just before vue-loader. 
The problem is vue-template-loader, its not compatible, i wanted a config that support everything, not simple.

Do you have some example of your implementation working? I would like to test it with sass/ts plus mixing normal vue with separated ones. And multiple components too.

Thanks.

**Comment by pksunkara** [comment]
No. I don't have an example. But I tested it locally only a month ago

Pavan Kumar Sunkara
