### ISSUE TITLE
Watch not working in vue files if this plugin is enabled

### ISSUE THREAD

**Issue by CKGrafico** [pksunkara/vue-builder-webpack-plugin#16]
If I have Single Components and multiple files components in the same project, like:
```
Example.Vue
Example2/
    Example2.js
    Example2.css
    Example2.html
```

Using this plugin the result will be
```
Example.Vue
Example2/
    Example2.vue
    Example2.js
    Example2.css
    Example2.html
```

If I use hot or watch with webpack 4 and I modify Example2.js/css/html everything is ok but if I modify Example.vue the watcher don't compile this file.

If I disable the plugin, the watcher works again.

**Comment by pksunkara** [comment]
So, you are saying this plugin is disabling the vue compiler with the above example? This plugin was never intended to work with normal `.vue` files directly, they were always supposed to be generated.

**Comment by CKGrafico** [comment]
Nice, can you tell me in which line are you disabling this and I will try to fix it?

**Comment by pksunkara** [comment]
[This](https://github.com/pksunkara/vue-builder-webpack-plugin/blob/master/index.js#L159) line, but if you remove, the plugin will go into infinite compilation

**Comment by CKGrafico** [comment]
I'll try thanks!
