### ISSUE TITLE
Suspected bug in folder mode

### ISSUE THREAD

**Issue by waxlamp** [pksunkara/vue-builder-webpack-plugin#23]
Hi again!

I suspect there may be a bug in folder mode. Since the virtual .vue file must be create next to a directory that contains the .vue.html etc. files, I believe the `relate()` function ([here](https://github.com/pksunkara/vue-builder-webpack-plugin/blob/master/index.js#L81)) should take a `folder` argument which, if true, should put one more `dirname` into the `src` attributes of the file sections, so that they say `./App/App.js.vue` instead of just `./App.js.vue`.

**Comment by pksunkara** [comment]
Nope, [this](https://github.com/pksunkara/vue-builder-webpack-plugin/blob/master/index.js#L147) line would take care of it.
