### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by theosherman** [pksunkara/vue-builder-webpack-plugin#3]
Using the webpack vue-cli template
Windows 10
Node 7.2.1

After running `npm run dev`, I see the message "Building vue files" however the dev server never responds back to the browser when hitting localhost:8080/

**Comment by pksunkara** [comment]
I am so sorry. I don't have notifications enabled for this repo and I completely missed everything. I am going to look into it this week.

**Comment by lukeawyatt** [comment]
+1, thanks @pksunkara

**Comment by xekri** [comment]
Hello, maybe you can check out this: [vue-separate-files-loader](https://github.com/xekri/vue-separate-files-loader). It definitely works, though may have some bugs.

**Comment by pksunkara** [comment]
Released 0.2.0
