### ISSUE TITLE
Can i store components in different folders inside 'src' folder?

### ISSUE THREAD

**Issue by Spiritized** [pksunkara/vue-builder-webpack-plugin#4]
For example, i have folder named 'MyComponent' inside 'src' folder. In 'MyComponent' folder i have all these required files - MyComponent.vue.js, MyComponent.vue.css, MyComponent.vue.html.
So, is it possible to config this plugin to work with this kind of structure, instead of have too much files from different component inside the 'src' folder?

**Comment by pksunkara** [comment]
I am so sorry. I don't have notifications enabled for this repo and I completely missed everything. I am going to look into it this week.

**Comment by lukeawyatt** [comment]
+1, thanks @pksunkara

**Comment by pksunkara** [comment]
Release 0.2.0
