### ISSUE TITLE
webpack watch: endless build loop

### ISSUE THREAD

**Issue by tweichart** [pksunkara/vue-builder-webpack-plugin#8]
Hey there,

it seems for me that there's an endless loop when using the watch option for the build.
I use [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) with the following webpack.mix.js:

```
let mix = require('laravel-mix')
let webpack = require('webpack')
let VueBuilder = require('vue-builder-webpack-plugin')

mix.webpackConfig(
    output: {
        chunkFilename: 'js/chunks/[name].js',
    },
    plugins: [
        //...
        new VueBuilder({
            path: 'resources/assets/js/vuejs/',
            folder: true,
        }),
       //...
    ],
    resolve: {
        alias: {
            '~vuejs': path.resolve(__dirname, './resources/assets/js/vuejs'),
            'scss': path.resolve(__dirname, './resources/assets/scss'),
        },
    }
    //...
})
//...
mix.js('resources/assets/js/init.js', 'public/js').extract([/*...*/])
mix.sass('resources/assets/scss/init.scss', 'public/css')
```
The files itself are created as in the example, so nothing special here. I use the async loading function of vuejs + webpack codesplitting, e.g.:
```
export default {
    props: [],
    components: {
        'mycomponent': () => import('~vuejs/components/MyConmpoent.vue'),
    },
}

```
This shouldn't interfere here though.
package.json:
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "vue-builder-webpack-plugin": "^0.3.1"
  },
  "dependencies": {
    "clean-webpack-plugin": "^0.1.18",
    "cross-env": "^5.1",
    "laravel-mix": "^1.0",
    "vue": "^2.1.10"
  }
}
```
Don't get confused because of the scripts here, it's just a default laravel setup ;-)

So all in all the `npm run dev` works like a charm, all files are created and correctly loaded in the browser. Using the `npm run watch` though leads to an endless loop:

![image](https://user-images.githubusercontent.com/1303151/36024693-c85f3746-0d90-11e8-91db-34496207988f.png)

This then keeps on going until you stop it.

I tried to add the webpack ignore plugin to the build
```
    new webpack.WatchIgnorePlugin([
        /\.vue/,
    ]),
```
this didn't help though, the watch keeps on going.

**Comment by pksunkara** [comment]
Which version are you using? I had the issue previously but I fixed it in the recent release.

**Comment by tweichart** [comment]
packages.json stated ^0.3.1

**Comment by pksunkara** [comment]
@tweichart Hey, were you able to fix this? I have a few free days coming up, I can go deep into this.

**Comment by pksunkara** [comment]
I have tried to really reproduce this since a few months, could never do it. It was always working for me. Sorry that I couldn't help.
